// Generated by CoffeeScript 1.9.3
var authorizationCodeDef, clientApplicationDef, getSettings, permissionDef, scopeDef, scopeMappingDef, tokenDef;

tokenDef = require('../../common/models/oauth-token.json');

authorizationCodeDef = require('../../common/models/oauth-authorization-code.json');

clientApplicationDef = require('../../common/models/oauth-client-application.json');

permissionDef = require('../../common/models/oauth-permission.json');

scopeDef = require('../../common/models/oauth-scope.json');

scopeMappingDef = require('../../common/models/oauth-scope-mapping.json');

getSettings = function(def) {
  var s, settings;
  settings = {};
  for (s in def) {
    if (s === 'name' || s === 'properties') {
      continue;
    } else {
      settings[s] = def[s];
    }
  }
  return settings;
};

module.exports = function(dataSource) {
  var OAuthAuthorizationCode, OAuthClientApplication, OAuthPermission, OAuthScope, OAuthScopeMapping, OAuthToken;
  OAuthToken = dataSource.createModel(tokenDef.name, tokenDef.properties, getSettings(tokenDef));
  OAuthAuthorizationCode = dataSource.createModel(authorizationCodeDef.name, authorizationCodeDef.properties, getSettings(authorizationCodeDef));
  OAuthClientApplication = dataSource.createModel(clientApplicationDef.name, clientApplicationDef.properties, getSettings(clientApplicationDef));
  OAuthPermission = dataSource.createModel(permissionDef.name, permissionDef.properties, getSettings(permissionDef));
  OAuthScope = dataSource.createModel(scopeDef.name, scopeDef.properties, scopeDef);
  OAuthScopeMapping = dataSource.createModel(scopeMappingDef.name, scopeMappingDef.properties, getSettings(scopeMappingDef));
  return {
    OAuthToken: OAuthToken,
    OAuthAuthorizationCode: OAuthAuthorizationCode,
    OAuthClientApplication: OAuthClientApplication,
    OAuthPermission: OAuthPermission,
    OAuthScope: OAuthScope,
    OAuthScopeMapping: OAuthScopeMapping
  };
};
