// Generated by CoffeeScript 1.9.0
var AbstractMonitor, RouteManager, RoutesMonitor, fs, _,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

fs = require('fs');

_ = require('lodash')._;

AbstractMonitor = require('api-hero').AbstractMonitor;

RoutesMonitor = (function(_super) {
  __extends(RoutesMonitor, _super);

  RoutesMonitor.prototype.__path = './views';

  function RoutesMonitor() {
    RoutesMonitor.__super__.constructor.call(this);
    this.startPolling(3);
  }

  RoutesMonitor.prototype.refresh = function(callback) {
    var ex;
    ex = [];
    return RouteManager.getInstance().load((function(_this) {
      return function(e, routes) {
        var idx, list, value, _i, _len;
        list = _.compact(_.map(routes, function(v) {
          var stats, _path;
          _path = v.route_file + ".js";
          try {
            stats = fs.statSync(_path);
          } catch (_error) {
            e = _error;
            return {
              name: v.route_file
            };
          }
          return null;
        }));
        for (_i = 0, _len = list.length; _i < _len; _i++) {
          value = list[_i];
          if (0 <= (idx = _this.getNames().indexOf(value.name))) {
            ex.push(value);
          }
        }
        if ((list = _.difference(list, ex)).length) {
          _this.__collection.addAll(list);
        }
        console.log(list);
        return typeof callback === "function" ? callback(e, list) : void 0;
      };
    })(this));
  };

  RoutesMonitor.prototype.startPolling = function() {
    console.log('startPolling');
    return this.__iVal != null ? this.__iVal : this.__iVal = fs.watch(this.__path, (function(_this) {
      return function(event, filename) {
        var e;
        try {
          return RouteManager.getInstance().load();
        } catch (_error) {
          e = _error;
          return console.log(e);
        } finally {
          _this.refresh();
        }
      };
    })(this));
  };

  return RoutesMonitor;

})(AbstractMonitor);

module.exports = RoutesMonitor;

RouteManager = require('./RouteManager');
