// Generated by CoffeeScript 1.9.0
var EventEmitter, RouteItem, RouteManager, fs, _, _path,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  __hasProp = {}.hasOwnProperty;

fs = require('fs-extra');

_ = require('lodash')._;

_path = require('path');

RouteItem = require('./RouteItem');

EventEmitter = require('events').EventEmitter;

RouteManager = (function(_super) {
  'use strict';
  __extends(RouteManager, _super);

  RouteManager.prototype.routes = [];

  RouteManager.prototype._viewsDir = "" + (app_root || '.') + _path.sep + "views";

  RouteManager.prototype._routesDir = "" + (app_root || '.') + _path.sep + "routes";

  function RouteManager() {
    fs.ensureDir(this._viewsDir, (function(_this) {
      return function() {
        return fs.ensureDir(_this._routesDir, function() {
          return _this.load(function(e, routes) {
            if (e != null) {
              return;
            }
            _this.routes = routes;
            return _this.emit('initialized', _this.routes);
          });
        });
      };
    })(this));
  }

  RouteManager.prototype.getRoute = function(route) {
    return _.where(this.routes, {
      route_file: route
    });
  };

  RouteManager.prototype.createRoute = function(routing, callback) {
    return (new RouteItem(routing)).save(callback);
  };

  RouteManager.prototype.destroyRoute = function(route, callback) {};

  RouteManager.prototype.listRoutes = function() {
    return this.routes;
  };

  RouteManager.prototype.load = function(callback) {
    var e, _routes;
    try {
      _routes = this.getpaths(this._viewsDir);
    } catch (_error) {
      e = _error;
      return typeof callback === "function" ? callback(e) : void 0;
    }
    return typeof callback === "function" ? callback(null, _routes) : void 0;
  };

  RouteManager.prototype.formatRoute = function(fname) {
    return fname.replace(/index/, '/').replace(/^(\/?[a-zA-Z0-9_]{1,}\/+)+(edit|index|show)$/, "$1:id/$2").replace(/\/\//, '/').replace(/^([a-zA-Z0-9_])+\/+$/, '$1');
  };

  RouteManager.prototype.getpaths = function(dir) {
    var e, file, itemName, list, name, p, paths, routeItem, stat, _i, _len;
    paths = [];
    if ((list = fs.readdirSync(dir)).length) {
      for (_i = 0, _len = list.length; _i < _len; _i++) {
        name = list[_i];
        if ((name.match(/^\./)) != null) {
          continue;
        }
        file = _path.join(dir, name);
        try {
          stat = fs.statSync(file);
        } catch (_error) {
          e = _error;
          throw new Error(e);
          return false;
        }
        if (stat != null ? stat.isDirectory() : void 0) {
          if (_path.basename(file).match(/^_+/)) {
            continue;
          }
          paths.push(this.getpaths(file));
        } else {
          itemName = name.split('.')[0];
          if ((name.match(/^[^_]+[a-zA-Z0-9_\.]+\.jade+$/)) == null) {
            continue;
          }
          p = new RegExp(this._viewsDir.replace(/\//, '\/'));
          routeItem = {
            name: itemName,
            file_type: 'jade',
            query_method: itemName === 'index' ? 'find' : 'findOne',
            route_file: "./" + (_path.join(this._routesDir, _path.basename(dir).replace(/views+/, ''), itemName)),
            template_file: _path.join(dir.split(/views+/).pop(), itemName),
            route: this.formatRoute(_path.join(_path.basename(dir).replace(/views+/, ''), itemName))
          };
          paths.push(routeItem);
        }
      }
    }
    return _.flatten(paths);
  };

  RouteManager.getInstance = function() {
    return this.__instance != null ? this.__instance : this.__instance = new this;
  };

  return RouteManager;

})(EventEmitter);

module.exports = RouteManager;
